/**
 * AI Engineering Assistant — recommendations only.
 * NEVER auto-creates PRs or modifies production.
 */

import type { CqiEngineeringRec } from "@/lib/cqi/types";

const SUBSYSTEM: Record<string, { files: string[]; subsystem: string }> = {
  clinical_realism: {
    subsystem: "case-engine / prompt clinical module",
    files: [
      "src/lib/case-engine/catalog.ts",
      "src/lib/ai/prompt-engine.ts",
      "personas/",
    ],
  },
  human_conversation: {
    subsystem: "prompt language + conversation fidelity",
    files: ["src/lib/ai/prompt-engine.ts", "src/components/VoiceSession.tsx"],
  },
  language: {
    subsystem: "i18n / personality language modules",
    files: ["messages/", "src/lib/ai/prompt-engine.ts", "personas/"],
  },
  voice: {
    subsystem: "voice pipeline / ElevenLabs",
    files: [
      "src/lib/voice/",
      "src/app/api/voice/tts/route.ts",
      "src/components/VoiceSession.tsx",
    ],
  },
  emotion: {
    subsystem: "patient affect expression",
    files: ["src/lib/ai/prompt-engine.ts", "src/lib/ai/patient-agent.ts"],
  },
  patient_behaviour: {
    subsystem: "clinical behaviour / defenses",
    files: ["src/lib/case-engine/", "src/lib/ai/prompt-engine.ts"],
  },
  educational_value: {
    subsystem: "ACE / CGE / presets",
    files: ["src/lib/ace/", "src/lib/cge/", "src/lib/instructor-presets/"],
  },
  assessment: {
    subsystem: "assessment examiner",
    files: ["src/lib/ai/assessment.ts", "src/app/api/sessions/[id]/end/route.ts"],
  },
  report: {
    subsystem: "session reports",
    files: ["src/components/ReportView.tsx", "src/lib/report-sign.ts"],
  },
  user_interface: {
    subsystem: "App Router UI",
    files: ["src/components/", "src/app/(app)/"],
  },
  performance: {
    subsystem: "API / voice latency",
    files: ["src/app/api/", "src/lib/voice/", "src/lib/rate-limit.ts"],
  },
  security: {
    subsystem: "auth / RLS / headers",
    files: [
      "src/lib/security-headers.ts",
      "src/middleware.ts",
      "supabase/migrations/",
    ],
  },
  research: {
    subsystem: "scientific / export",
    files: ["src/lib/cqi/", "docs/"],
  },
  other: {
    subsystem: "cross-cutting",
    files: ["src/"],
  },
};

export function buildEngineeringRecommendation(input: {
  title: string;
  category: string;
  severity: string;
  report_count: number;
  sample_texts: string[];
  disorders: string[];
  languages: string[];
  prompts: string[];
}): CqiEngineeringRec {
  const map = SUBSYSTEM[input.category] ?? SUBSYSTEM.other!;
  const priority =
    input.severity === "critical"
      ? "p0"
      : input.severity === "high"
        ? "p1"
        : input.severity === "medium"
          ? "p2"
          : "p3";

  const root_cause = [
    `Repeated expert feedback (${input.report_count}) in category ${input.category}.`,
    input.disorders.length
      ? `Affected disorders: ${input.disorders.join(", ")}.`
      : "Disorder scope unclear / cross-cutting.",
    input.languages.length
      ? `Languages: ${input.languages.join(", ")}.`
      : "",
    input.prompts.length
      ? `Prompt versions: ${input.prompts.join(", ")}.`
      : "",
    "Likely subsystem: " + map.subsystem + ".",
  ]
    .filter(Boolean)
    .join(" ");

  const samples = input.sample_texts
    .map((t, i) => `${i + 1}. ${t.slice(0, 240)}`)
    .join("\n");

  const github_issue_md = [
    `## CQI Cluster: ${input.title}`,
    "",
    `**Priority:** ${priority}`,
    `**Severity:** ${input.severity}`,
    `**Reports:** ${input.report_count}`,
    "",
    "### Root cause (draft)",
    root_cause,
    "",
    "### Sample observations",
    samples || "_none_",
    "",
    "### Affected files (suggested)",
    ...map.files.map((f) => `- \`${f}\``),
    "",
    "### Acceptance criteria",
    "- Expert re-review does not reproduce the clustered issue on the same disorder/language pack",
    "- Regression test added where automatable",
    "- No automatic production deploy from CQI",
    "",
    "> Generated by CQI Engineering Assistant — **requires human approval**. Do not auto-merge.",
  ].join("\n");

  const cursor_prompt = [
    `You are fixing a VPsych CQI cluster: ${input.title}.`,
    `Category=${input.category}; severity=${input.severity}; reports=${input.report_count}.`,
    `Focus subsystems: ${map.subsystem}.`,
    `Likely files: ${map.files.join(", ")}.`,
    `Disorders: ${input.disorders.join(", ") || "n/a"}; languages: ${input.languages.join(", ") || "n/a"}.`,
    "Constraints: do not weaken RLS/security; do not claim clinical validation; add/adjust tests; do not auto-create extra PRs beyond the assigned branch.",
    "Sample feedback:",
    samples || "(none)",
  ].join("\n");

  return {
    title: input.title,
    root_cause,
    affected_files: map.files,
    affected_subsystem: map.subsystem,
    risk:
      priority === "p0" || priority === "p1"
        ? "High educational/clinical authenticity risk if unaddressed"
        : "Moderate quality risk",
    priority,
    regression_requirements:
      "Re-run affected disorder session smoke + CQI fingerprint should not recur on golden transcript where applicable",
    acceptance_criteria:
      "Human approver confirms cluster status→resolved after verified fix; CQI vault retains original flags",
    github_issue_md,
    cursor_prompt,
    requires_human_approval: true,
  };
}
