import type { InstructorPreset } from "@/lib/instructor-presets/types";

export const BUILTIN_PRESETS: InstructorPreset[] = [
  {
    id: "f1000000-0000-4000-8000-000000000001",
    slug: "suicide-risk-resident-en",
    name: "Suicide Risk Assessment — Psychiatry Resident",
    description:
      "Practice calm, specific suicide risk assessment. Engine selects diagnosis automatically.",
    specialty: "general_adult_psychiatry",
    target_learner: "psychiatry_resident",
    learning_level: "residency",
    clinical_rotation: "acute_care",
    assessment_type: "risk_assessment",
    primary_objective: "suicide_assessment",
    secondary_objectives: [
      "risk_assessment",
      "diagnostic_interview",
      "crisis_intervention",
    ],
    difficulty: "intermediate",
    time_limit_minutes: 30,
    language: "en-US",
    culture: "north_american_urban",
    therapy_modality: "crisis_intervention",
    randomization_level: "moderate",
    grading_mode: "practice",
    feedback_mode: "realtime_coaching",
    voice_enabled: true,
    assessment_enabled: true,
    record_session: true,
    allow_hints: true,
    allow_pause: true,
    allow_restart: true,
    advanced_mode: false,
    scenario_template_slug: "ptsd-risk-assessment-en",
    preferred_template_slugs: [
      "ptsd-risk-assessment-en",
      "adult-mdd-initial-en",
    ],
    clinical_constraints: [],
    required_competencies: [
      {
        competency_id: "safety",
        label: "Safety assessment",
        required: true,
        weight: 2,
        max_score: 5,
      },
      {
        competency_id: "alliance",
        label: "Therapeutic alliance",
        required: true,
        weight: 1.2,
        max_score: 5,
      },
      {
        competency_id: "empathy",
        label: "Empathy",
        required: true,
        weight: 1,
        max_score: 5,
      },
    ],
    optional_competencies: [
      {
        competency_id: "documentation",
        label: "Documentation",
        required: false,
        weight: 0.8,
        max_score: 5,
      },
    ],
    grading: {
      pass_threshold: 70,
      outstanding_threshold: 90,
      critical_mistakes: [
        "missed_si",
        "forced_trauma_disclosure",
        "no_safety_plan",
      ],
      automatic_deductions: { missed_si: 20 },
      dimensions: [
        "diagnostic_accuracy",
        "dsm_reasoning",
        "communication",
        "empathy",
        "therapeutic_alliance",
        "risk_assessment",
        "safety_planning",
        "documentation",
        "professionalism",
        "time_management",
      ],
      report_sections: [
        "score",
        "strengths",
        "weaknesses",
        "missed_opportunities",
        "recommendations",
      ],
    },
    enabled: true,
    version: 1,
  },
  {
    id: "f1000000-0000-4000-8000-000000000002",
    slug: "osce-diagnostic-interview-ar",
    name: "OSCE Diagnostic Interview — Arabic",
    description:
      "Timed OSCE station. Engine selects diagnosis; no hints.",
    specialty: "general_adult_psychiatry",
    target_learner: "osce_candidate",
    learning_level: "undergraduate",
    clinical_rotation: "osce",
    assessment_type: "osce_examination",
    primary_objective: "osce_examination",
    secondary_objectives: [
      "diagnostic_interview",
      "mental_status_examination",
    ],
    difficulty: "advanced",
    time_limit_minutes: 20,
    language: "ar-JO",
    culture: "levantine_arabic",
    therapy_modality: "cbt",
    randomization_level: "low",
    grading_mode: "osce",
    feedback_mode: "none",
    voice_enabled: true,
    assessment_enabled: true,
    record_session: true,
    allow_hints: false,
    allow_pause: false,
    allow_restart: false,
    advanced_mode: false,
    scenario_template_slug: "adult-gad-osce-ar",
    preferred_template_slugs: ["adult-gad-osce-ar", "adult-mdd-initial-en"],
    clinical_constraints: [
      { constraint_type: "required_locale", value: "ar-JO" },
    ],
    required_competencies: [
      {
        competency_id: "communication",
        label: "Communication",
        required: true,
        weight: 1.5,
        max_score: 5,
      },
      {
        competency_id: "mse",
        label: "Mental status exam",
        required: true,
        weight: 1.2,
        max_score: 5,
      },
      {
        competency_id: "time",
        label: "Time management",
        required: true,
        weight: 1,
        max_score: 5,
      },
    ],
    optional_competencies: [],
    grading: {
      pass_threshold: 65,
      outstanding_threshold: 90,
      critical_mistakes: ["locale_leakage", "incomplete_mse"],
      automatic_deductions: { locale_leakage: 15 },
      dimensions: [
        "communication",
        "diagnostic_accuracy",
        "mental_status",
        "time_management",
        "professionalism",
      ],
      report_sections: [
        "score",
        "strengths",
        "weaknesses",
        "missed_opportunities",
        "recommendations",
      ],
    },
    enabled: true,
    version: 1,
  },
  {
    id: "f1000000-0000-4000-8000-000000000003",
    slug: "cbt-skills-gp-en",
    name: "CBT Skills — General Practitioner",
    description:
      "Primary-care CBT skills with auto-selected mood/anxiety case.",
    specialty: "primary_care_mental_health",
    target_learner: "general_practitioner",
    learning_level: "continuing_education",
    clinical_rotation: "primary_care",
    assessment_type: "cbt_session",
    primary_objective: "cbt_skills",
    secondary_objectives: ["psychoeducation", "treatment_planning"],
    difficulty: "beginner",
    time_limit_minutes: 45,
    language: "en-US",
    culture: "north_american_urban",
    therapy_modality: "cbt",
    randomization_level: "low",
    grading_mode: "practice",
    feedback_mode: "end_of_session",
    voice_enabled: true,
    assessment_enabled: true,
    record_session: true,
    allow_hints: true,
    allow_pause: true,
    allow_restart: true,
    advanced_mode: false,
    scenario_template_slug: "adult-mdd-initial-en",
    preferred_template_slugs: ["adult-mdd-initial-en"],
    clinical_constraints: [
      { constraint_type: "allowed_disorder", value: "mdd-recurrent-moderate" },
      { constraint_type: "allowed_disorder", value: "gad-with-panic" },
      { constraint_type: "allowed_disorder", value: "panic-disorder" },
      {
        constraint_type: "forbidden_comorbidity",
        value: "alcohol-use-disorder",
      },
      { constraint_type: "max_comorbidities", value: "1" },
    ] as InstructorPreset["clinical_constraints"],
    required_competencies: [
      {
        competency_id: "cbt_structure",
        label: "CBT structure",
        required: true,
        weight: 1.5,
        max_score: 5,
      },
      {
        competency_id: "alliance",
        label: "Alliance",
        required: true,
        weight: 1,
        max_score: 5,
      },
    ],
    optional_competencies: [],
    grading: {
      pass_threshold: 60,
      outstanding_threshold: 85,
      critical_mistakes: [
        "advice_before_agenda",
        "ignored_homework_barriers",
      ],
      automatic_deductions: {},
      dimensions: [
        "cbt_skills",
        "communication",
        "treatment_planning",
        "psychoeducation",
        "alliance",
      ],
      report_sections: [
        "score",
        "strengths",
        "weaknesses",
        "missed_opportunities",
        "recommendations",
      ],
    },
    enabled: true,
    version: 1,
  },
  {
    id: "f1000000-0000-4000-8000-000000000004",
    slug: "foundation-interview-medstudent-en",
    name: "Foundation Diagnostic Interview — Medical Student",
    description:
      "Undergraduate CBME station: alliance, MSE basics, and structured history.",
    specialty: "general_adult_psychiatry",
    target_learner: "medical_student",
    learning_level: "undergraduate",
    clinical_rotation: "clerkship",
    assessment_type: "initial_assessment",
    primary_objective: "diagnostic_interview",
    secondary_objectives: [
      "mental_status_examination",
      "psychoeducation",
      "shared_decision_making",
    ],
    difficulty: "beginner",
    time_limit_minutes: 30,
    language: "en-US",
    culture: "north_american_urban",
    therapy_modality: "supportive",
    randomization_level: "low",
    grading_mode: "practice",
    feedback_mode: "realtime_coaching",
    voice_enabled: true,
    assessment_enabled: true,
    record_session: true,
    allow_hints: true,
    allow_pause: true,
    allow_restart: true,
    advanced_mode: false,
    scenario_template_id: "e1000000-0000-4000-8000-000000000001",
    preferred_template_slugs: ["adult-mdd-initial-en"],
    clinical_constraints: [],
    required_competencies: [
      {
        competency_id: "therapeutic_alliance",
        label: "Therapeutic alliance",
        required: true,
        weight: 1.5,
        max_score: 5,
      },
      {
        competency_id: "diagnostic_interview",
        label: "Diagnostic interview",
        required: true,
        weight: 1.5,
        max_score: 5,
      },
      {
        competency_id: "empathy",
        label: "Empathy",
        required: true,
        weight: 1,
        max_score: 5,
      },
    ],
    optional_competencies: [],
    grading: {
      pass_threshold: 60,
      outstanding_threshold: 85,
      critical_mistakes: ["hostile_stance", "no_agenda"],
      automatic_deductions: {},
      dimensions: [
        "communication",
        "empathy",
        "therapeutic_alliance",
        "dsm_reasoning",
      ],
      report_sections: [
        "score",
        "strengths",
        "weaknesses",
        "missed_opportunities",
        "recommendations",
      ],
    },
    enabled: true,
    version: 1,
  },
  {
    id: "f1000000-0000-4000-8000-000000000005",
    slug: "mi-counselor-en",
    name: "Motivational Interviewing — Counselor",
    description:
      "Counseling CBME: MI spirit, alliance, and psychoeducation on substance/mood overlap.",
    specialty: "counselling",
    target_learner: "counselor",
    learning_level: "postgraduate",
    clinical_rotation: "outpatient",
    assessment_type: "initial_assessment",
    primary_objective: "motivational_interviewing",
    secondary_objectives: [
      "psychoeducation",
      "substance_use_assessment",
    ],
    difficulty: "intermediate",
    time_limit_minutes: 40,
    language: "en-US",
    culture: "north_american_urban",
    therapy_modality: "motivational_interviewing",
    randomization_level: "moderate",
    grading_mode: "practice",
    feedback_mode: "end_of_session",
    voice_enabled: true,
    assessment_enabled: true,
    record_session: true,
    allow_hints: true,
    allow_pause: true,
    allow_restart: true,
    advanced_mode: false,
    scenario_template_id: "e1000000-0000-4000-8000-000000000001",
    preferred_template_slugs: ["adult-mdd-initial-en"],
    clinical_constraints: [],
    required_competencies: [
      {
        competency_id: "therapeutic_alliance",
        label: "Alliance",
        required: true,
        weight: 1.5,
        max_score: 5,
      },
      {
        competency_id: "empathy",
        label: "Empathy",
        required: true,
        weight: 1.5,
        max_score: 5,
      },
    ],
    optional_competencies: [],
    grading: {
      pass_threshold: 65,
      outstanding_threshold: 88,
      critical_mistakes: ["advice_before_agenda"],
      automatic_deductions: {},
      dimensions: [
        "communication",
        "empathy",
        "therapeutic_alliance",
        "psychoeducation",
      ],
      report_sections: [
        "score",
        "strengths",
        "weaknesses",
        "missed_opportunities",
        "recommendations",
      ],
    },
    enabled: true,
    version: 1,
  },
  {
    id: "f1000000-0000-4000-8000-000000000006",
    slug: "cbt-psychologist-en",
    name: "CBT Formulation — Psychologist",
    description:
      "Psychology CBME: CBT skills, formulation, and collaborative treatment planning.",
    specialty: "clinical_psychology",
    target_learner: "psychologist",
    learning_level: "postgraduate",
    clinical_rotation: "outpatient",
    assessment_type: "cbt_session",
    primary_objective: "cbt_skills",
    secondary_objectives: [
      "treatment_planning",
      "differential_diagnosis",
      "psychoeducation",
    ],
    difficulty: "intermediate",
    time_limit_minutes: 45,
    language: "en-US",
    culture: "north_american_urban",
    therapy_modality: "cbt",
    randomization_level: "moderate",
    grading_mode: "practice",
    feedback_mode: "end_of_session",
    voice_enabled: true,
    assessment_enabled: true,
    record_session: true,
    allow_hints: true,
    allow_pause: true,
    allow_restart: true,
    advanced_mode: false,
    scenario_template_id: "e1000000-0000-4000-8000-000000000001",
    preferred_template_slugs: ["adult-mdd-initial-en"],
    clinical_constraints: [],
    required_competencies: [
      {
        competency_id: "cbt_skills",
        label: "CBT skills",
        required: true,
        weight: 1.5,
        max_score: 5,
      },
      {
        competency_id: "therapeutic_alliance",
        label: "Alliance",
        required: true,
        weight: 1,
        max_score: 5,
      },
    ],
    optional_competencies: [],
    grading: {
      pass_threshold: 70,
      outstanding_threshold: 90,
      critical_mistakes: ["advice_before_agenda"],
      automatic_deductions: {},
      dimensions: [
        "cbt_skills",
        "treatment_planning",
        "communication",
        "alliance",
      ],
      report_sections: [
        "score",
        "strengths",
        "weaknesses",
        "missed_opportunities",
        "recommendations",
      ],
    },
    enabled: true,
    version: 1,
  },
  {
    id: "f1000000-0000-4000-8000-000000000007",
    slug: "complex-formulation-consultant-en",
    name: "Complex Formulation — Consultant Psychiatrist",
    description:
      "Fellowship-level formulation and differential for complex mood/psychosis presentations.",
    specialty: "general_adult_psychiatry",
    target_learner: "consultant_psychiatrist",
    learning_level: "fellowship",
    clinical_rotation: "consultation_liaison",
    assessment_type: "initial_assessment",
    primary_objective: "differential_diagnosis",
    secondary_objectives: [
      "treatment_planning",
      "diagnostic_interview",
      "risk_assessment",
    ],
    difficulty: "expert",
    time_limit_minutes: 45,
    language: "en-US",
    culture: "north_american_urban",
    therapy_modality: "psychodynamic",
    randomization_level: "high",
    grading_mode: "supervisor_review",
    feedback_mode: "supervisor_only",
    voice_enabled: true,
    assessment_enabled: true,
    record_session: false,
    allow_hints: false,
    allow_pause: true,
    allow_restart: false,
    advanced_mode: true,
    scenario_template_id: "e1000000-0000-4000-8000-000000000001",
    preferred_template_slugs: [
      "adult-mdd-initial-en",
      "ptsd-risk-assessment-en",
    ],
    clinical_constraints: [],
    required_competencies: [
      {
        competency_id: "differential_diagnosis",
        label: "Differential diagnosis",
        required: true,
        weight: 2,
        max_score: 5,
      },
      {
        competency_id: "case_formulation",
        label: "Case formulation",
        required: true,
        weight: 1.8,
        max_score: 5,
      },
      {
        competency_id: "therapeutic_alliance",
        label: "Therapeutic alliance",
        required: true,
        weight: 1.2,
        max_score: 5,
      },
    ],
    optional_competencies: [
      {
        competency_id: "dsm5_reasoning",
        label: "DSM-5 diagnostic reasoning",
        required: false,
        weight: 1,
        max_score: 5,
      },
    ],
    grading: {
      pass_threshold: 80,
      outstanding_threshold: 95,
      critical_mistakes: [
        "missed_si",
        "unsafe_medication_combination",
        "premature_closure",
      ],
      automatic_deductions: {},
      dimensions: [
        "diagnostic_accuracy",
        "dsm_reasoning",
        "differential",
        "formulation",
        "communication",
        "empathy",
        "therapeutic_alliance",
        "risk_assessment",
        "treatment_planning",
        "documentation",
        "professionalism",
        "time_management",
      ],
      report_sections: [
        "score",
        "strengths",
        "weaknesses",
        "missed_opportunities",
        "recommendations",
      ],
    },
    enabled: true,
    version: 1,
  },
];

export function findPresetBySlug(slug: string): InstructorPreset | undefined {
  return BUILTIN_PRESETS.find((p) => p.slug === slug && p.enabled);
}

export function findPresetById(id: string): InstructorPreset | undefined {
  return BUILTIN_PRESETS.find((p) => p.id === id && p.enabled);
}

export function listBuiltinPresets(): InstructorPreset[] {
  return BUILTIN_PRESETS.filter((p) => p.enabled);
}

/**
 * Map a DB instructor_presets row into a valid InstructorPreset.
 * Used when a seeded preset exists in Postgres but is missing from builtins
 * (or builtins are stale). Never leave target_learner / assessment_type undefined.
 */
export function mapDbRowToPreset(row: Record<string, unknown>): InstructorPreset {
  const secondary = Array.isArray(row.secondary_objectives)
    ? (row.secondary_objectives as InstructorPreset["secondary_objectives"])
    : [];
  return {
    id: String(row.id),
    slug: String(row.slug),
    name: String(row.name),
    description: (row.description as string) ?? null,
    specialty: (row.specialty as InstructorPreset["specialty"]) ?? "general_adult_psychiatry",
    target_learner:
      (row.target_learner as InstructorPreset["target_learner"]) ??
      "psychiatry_resident",
    learning_level:
      (row.learning_level as InstructorPreset["learning_level"]) ?? "residency",
    clinical_rotation: (row.clinical_rotation as string) ?? null,
    assessment_type:
      (row.assessment_type as InstructorPreset["assessment_type"]) ??
      "initial_assessment",
    primary_objective:
      (row.primary_objective as InstructorPreset["primary_objective"]) ??
      "diagnostic_interview",
    secondary_objectives: secondary,
    difficulty: (row.difficulty as InstructorPreset["difficulty"]) ?? "intermediate",
    time_limit_minutes:
      (row.time_limit_minutes as InstructorPreset["time_limit_minutes"]) ?? 30,
    language: String(row.language ?? "en-US"),
    culture: (row.culture as string) ?? null,
    therapy_modality:
      (row.therapy_modality as InstructorPreset["therapy_modality"]) ?? "supportive",
    randomization_level:
      (row.randomization_level as InstructorPreset["randomization_level"]) ??
      "moderate",
    grading_mode: (row.grading_mode as InstructorPreset["grading_mode"]) ?? "practice",
    feedback_mode:
      (row.feedback_mode as InstructorPreset["feedback_mode"]) ?? "end_of_session",
    voice_enabled: Boolean(row.voice_enabled ?? true),
    assessment_enabled: Boolean(row.assessment_enabled ?? true),
    record_session: Boolean(row.record_session ?? true),
    allow_hints: Boolean(row.allow_hints ?? false),
    allow_pause: Boolean(row.allow_pause ?? true),
    allow_restart: Boolean(row.allow_restart ?? false),
    advanced_mode: Boolean(row.advanced_mode ?? false),
    scenario_template_id: (row.scenario_template_id as string) ?? null,
    preferred_template_slugs: Array.isArray(row.preferred_template_slugs)
      ? (row.preferred_template_slugs as string[])
      : [],
    clinical_constraints: [],
    required_competencies: [],
    optional_competencies: [],
    grading: {
      pass_threshold: 70,
      outstanding_threshold: 90,
      critical_mistakes: [],
      automatic_deductions: {},
      dimensions: ["alliance", "assessment"],
      report_sections: ["narrative", "scores"],
    },
    enabled: Boolean(row.enabled ?? true),
    version: Number(row.version ?? 1),
  };
}
