import type { InstructorPreset } from "@/lib/instructor-presets/types";

export const BUILTIN_PRESETS: InstructorPreset[] = [
  {
    id: "f1000000-0000-4000-8000-000000000001",
    slug: "suicide-risk-resident-en",
    name: "Suicide Risk Assessment — Psychiatry Resident",
    description:
      "Practice calm, specific suicide risk assessment. Engine selects diagnosis automatically.",
    specialty: "general_adult_psychiatry",
    target_learner: "psychiatry_resident",
    learning_level: "residency",
    clinical_rotation: "acute_care",
    assessment_type: "risk_assessment",
    primary_objective: "suicide_assessment",
    secondary_objectives: [
      "risk_assessment",
      "diagnostic_interview",
      "crisis_intervention",
    ],
    difficulty: "intermediate",
    time_limit_minutes: 30,
    language: "en-US",
    culture: "north_american_urban",
    therapy_modality: "crisis_intervention",
    randomization_level: "moderate",
    grading_mode: "practice",
    feedback_mode: "realtime_coaching",
    voice_enabled: true,
    assessment_enabled: true,
    record_session: true,
    allow_hints: true,
    allow_pause: true,
    allow_restart: true,
    advanced_mode: false,
    scenario_template_slug: "ptsd-risk-assessment-en",
    preferred_template_slugs: [
      "ptsd-risk-assessment-en",
      "adult-mdd-initial-en",
    ],
    clinical_constraints: [],
    required_competencies: [
      {
        competency_id: "safety",
        label: "Safety assessment",
        required: true,
        weight: 2,
        max_score: 5,
      },
      {
        competency_id: "alliance",
        label: "Therapeutic alliance",
        required: true,
        weight: 1.2,
        max_score: 5,
      },
      {
        competency_id: "empathy",
        label: "Empathy",
        required: true,
        weight: 1,
        max_score: 5,
      },
    ],
    optional_competencies: [
      {
        competency_id: "documentation",
        label: "Documentation",
        required: false,
        weight: 0.8,
        max_score: 5,
      },
    ],
    grading: {
      pass_threshold: 70,
      outstanding_threshold: 90,
      critical_mistakes: [
        "missed_si",
        "forced_trauma_disclosure",
        "no_safety_plan",
      ],
      automatic_deductions: { missed_si: 20 },
      dimensions: [
        "diagnostic_accuracy",
        "dsm_reasoning",
        "communication",
        "empathy",
        "therapeutic_alliance",
        "risk_assessment",
        "safety_planning",
        "documentation",
        "professionalism",
        "time_management",
      ],
      report_sections: [
        "score",
        "strengths",
        "weaknesses",
        "missed_opportunities",
        "recommendations",
      ],
    },
    enabled: true,
    version: 1,
  },
  {
    id: "f1000000-0000-4000-8000-000000000002",
    slug: "osce-diagnostic-interview-ar",
    name: "OSCE Diagnostic Interview — Arabic",
    description:
      "Timed OSCE station. Engine selects diagnosis; no hints.",
    specialty: "general_adult_psychiatry",
    target_learner: "osce_candidate",
    learning_level: "undergraduate",
    clinical_rotation: "osce",
    assessment_type: "osce_examination",
    primary_objective: "osce_examination",
    secondary_objectives: [
      "diagnostic_interview",
      "mental_status_examination",
    ],
    difficulty: "advanced",
    time_limit_minutes: 20,
    language: "ar-JO",
    culture: "levantine_arabic",
    therapy_modality: "cbt",
    randomization_level: "low",
    grading_mode: "osce",
    feedback_mode: "none",
    voice_enabled: true,
    assessment_enabled: true,
    record_session: true,
    allow_hints: false,
    allow_pause: false,
    allow_restart: false,
    advanced_mode: false,
    scenario_template_slug: "adult-gad-osce-ar",
    preferred_template_slugs: ["adult-gad-osce-ar", "adult-mdd-initial-en"],
    clinical_constraints: [
      { constraint_type: "required_locale", value: "ar-JO" },
    ],
    required_competencies: [
      {
        competency_id: "communication",
        label: "Communication",
        required: true,
        weight: 1.5,
        max_score: 5,
      },
      {
        competency_id: "mse",
        label: "Mental status exam",
        required: true,
        weight: 1.2,
        max_score: 5,
      },
      {
        competency_id: "time",
        label: "Time management",
        required: true,
        weight: 1,
        max_score: 5,
      },
    ],
    optional_competencies: [],
    grading: {
      pass_threshold: 65,
      outstanding_threshold: 90,
      critical_mistakes: ["locale_leakage", "incomplete_mse"],
      automatic_deductions: { locale_leakage: 15 },
      dimensions: [
        "communication",
        "diagnostic_accuracy",
        "mental_status",
        "time_management",
        "professionalism",
      ],
      report_sections: [
        "score",
        "strengths",
        "weaknesses",
        "missed_opportunities",
        "recommendations",
      ],
    },
    enabled: true,
    version: 1,
  },
  {
    id: "f1000000-0000-4000-8000-000000000003",
    slug: "cbt-skills-gp-en",
    name: "CBT Skills — General Practitioner",
    description:
      "Primary-care CBT skills with auto-selected mood/anxiety case.",
    specialty: "primary_care_mental_health",
    target_learner: "general_practitioner",
    learning_level: "continuing_education",
    clinical_rotation: "primary_care",
    assessment_type: "cbt_session",
    primary_objective: "cbt_skills",
    secondary_objectives: ["psychoeducation", "treatment_planning"],
    difficulty: "beginner",
    time_limit_minutes: 45,
    language: "en-US",
    culture: "north_american_urban",
    therapy_modality: "cbt",
    randomization_level: "moderate",
    grading_mode: "practice",
    feedback_mode: "end_of_session",
    voice_enabled: true,
    assessment_enabled: true,
    record_session: true,
    allow_hints: true,
    allow_pause: true,
    allow_restart: true,
    advanced_mode: false,
    scenario_template_slug: "adult-mdd-initial-en",
    preferred_template_slugs: ["adult-mdd-initial-en"],
    clinical_constraints: [],
    required_competencies: [
      {
        competency_id: "cbt_structure",
        label: "CBT structure",
        required: true,
        weight: 1.5,
        max_score: 5,
      },
      {
        competency_id: "alliance",
        label: "Alliance",
        required: true,
        weight: 1,
        max_score: 5,
      },
    ],
    optional_competencies: [],
    grading: {
      pass_threshold: 60,
      outstanding_threshold: 85,
      critical_mistakes: [
        "advice_before_agenda",
        "ignored_homework_barriers",
      ],
      automatic_deductions: {},
      dimensions: [
        "cbt_skills",
        "communication",
        "treatment_planning",
        "psychoeducation",
        "alliance",
      ],
      report_sections: [
        "score",
        "strengths",
        "weaknesses",
        "missed_opportunities",
        "recommendations",
      ],
    },
    enabled: true,
    version: 1,
  },
];

export function findPresetBySlug(slug: string): InstructorPreset | undefined {
  return BUILTIN_PRESETS.find((p) => p.slug === slug && p.enabled);
}

export function findPresetById(id: string): InstructorPreset | undefined {
  return BUILTIN_PRESETS.find((p) => p.id === id && p.enabled);
}

export function listBuiltinPresets(): InstructorPreset[] {
  return BUILTIN_PRESETS.filter((p) => p.enabled);
}
