import { DISORDER_IDS } from "@/lib/case-engine/catalog";
import type { ClinicalScenarioTemplate } from "@/lib/scenario-templates/types";

/** Builtin templates used offline / when DB unavailable. */
export const BUILTIN_TEMPLATES: ClinicalScenarioTemplate[] = [
  {
    id: "e1000000-0000-4000-8000-000000000001",
    slug: "adult-mdd-initial-en",
    name: "Adult MDD — Initial Assessment (English)",
    description:
      "Standardized initial assessment for moderate recurrent MDD with optional GAD comorbidity.",
    specialty: "general_adult_psychiatry",
    target_learners: [
      "psychiatry_resident",
      "gp",
      "counsellor",
      "clinical_psychology",
    ],
    estimated_duration_minutes: 40,
    difficulty: "intermediate",
    language: "en-US",
    culture: "north_american_urban",
    therapy_modality: "cbt",
    primary_diagnosis_id: DISORDER_IDS.mdd,
    primary_diagnosis_slug: "mdd-recurrent-moderate",
    allowed_comorbidity_slugs: ["gad-with-panic", "alcohol-use-disorder"],
    excluded_diagnosis_slugs: ["bipolar-mania"],
    severity: "moderate",
    risk_level: "moderate",
    assessment_type: "initial_assessment",
    default_persona_slug: "maya-chen",
    randomization_level: "moderate",
    memory_mode: "case_isolated",
    grading_rubric: {
      pass_threshold: 60,
      outstanding_threshold: 85,
      critical_mistakes: [
        "ignoring passive SI",
        "prescribing without bipolar screen",
      ],
      automatic_deductions: { missed_safety_assessment: 15 },
    },
    report_template: {
      sections: ["summary", "risk", "formulation", "plan"],
    },
    learning_objectives: [
      {
        category: "skills",
        statement: "Conduct a structured mood and risk assessment",
      },
      {
        category: "risk",
        statement: "Elicit passive SI with calm specific questioning",
      },
      {
        category: "dsm_reasoning",
        statement: "Defend MDD severity and anxious distress specifier",
      },
      {
        category: "differential_diagnosis",
        statement: "Screen for bipolarity before antidepressant discussion",
      },
      {
        category: "therapeutic_alliance",
        statement: "Validate affect before behavioural activation",
      },
    ],
    clinical_competencies: [
      {
        competency_id: "alliance",
        label: "Therapeutic alliance",
        weight: 1.2,
        max_score: 5,
      },
      {
        competency_id: "safety",
        label: "Safety assessment",
        weight: 1.5,
        max_score: 5,
        critical: true,
        auto_deduction: 15,
        excellent_marker: "Specific SI questions without alarm",
      },
      {
        competency_id: "formulation",
        label: "Clinical formulation",
        weight: 1,
        max_score: 5,
      },
      {
        competency_id: "dsm",
        label: "DSM reasoning",
        weight: 1,
        max_score: 5,
      },
    ],
    enabled: true,
    version: 1,
  },
  {
    id: "e1000000-0000-4000-8000-000000000002",
    slug: "adult-gad-osce-ar",
    name: "Adult GAD — OSCE (Arabic)",
    description:
      "OSCE-style GAD with panic features for Arabic Levantine simulation.",
    specialty: "general_adult_psychiatry",
    target_learners: ["psychiatry_resident", "medical_student"],
    estimated_duration_minutes: 20,
    difficulty: "advanced",
    language: "ar-JO",
    culture: "levantine_arabic",
    therapy_modality: "cbt",
    primary_diagnosis_id: DISORDER_IDS.gad,
    primary_diagnosis_slug: "gad-with-panic",
    allowed_comorbidity_slugs: ["mdd-recurrent-moderate", "adult-adhd"],
    excluded_diagnosis_slugs: ["bipolar-mania", "delirium"],
    severity: "moderate",
    risk_level: "low",
    assessment_type: "osce_examination",
    default_persona_slug: "jordan-hale",
    randomization_level: "low",
    memory_mode: "case_isolated",
    grading_rubric: {
      pass_threshold: 65,
      outstanding_threshold: 90,
      critical_mistakes: [
        "reassurance-seeking loop",
        "missing panic assessment",
      ],
    },
    report_template: {
      sections: ["osce_checklist", "risk", "communication"],
    },
    learning_objectives: [
      {
        category: "communication",
        statement: "Conduct OSCE interview in Arabic without locale leakage",
      },
      {
        category: "skills",
        statement: "Map worry domains and panic phenomenology",
      },
      {
        category: "icd_reasoning",
        statement: "Map GAD to ICD-11 6B00",
      },
    ],
    clinical_competencies: [
      {
        competency_id: "communication",
        label: "Communication",
        weight: 1.5,
        max_score: 5,
      },
      {
        competency_id: "anxiety_assessment",
        label: "Anxiety assessment",
        weight: 1.2,
        max_score: 5,
        critical: true,
      },
    ],
    enabled: true,
    version: 1,
  },
  {
    id: "e1000000-0000-4000-8000-000000000003",
    slug: "ptsd-risk-assessment-en",
    name: "PTSD — Risk Assessment (English)",
    description:
      "Trauma-informed risk assessment with MDD comorbidity allowed.",
    specialty: "emergency_psychiatry",
    target_learners: [
      "psychiatry_resident",
      "emergency_physician",
      "crisis_worker",
    ],
    estimated_duration_minutes: 30,
    difficulty: "advanced",
    language: "en-US",
    culture: "north_american_urban",
    therapy_modality: "crisis_intervention",
    primary_diagnosis_id: DISORDER_IDS.ptsd,
    primary_diagnosis_slug: "ptsd",
    allowed_comorbidity_slugs: [
      "mdd-recurrent-moderate",
      "alcohol-use-disorder",
    ],
    excluded_diagnosis_slugs: ["delirium"],
    severity: "severe",
    risk_level: "high",
    assessment_type: "risk_assessment",
    // Do not bind MDD persona biography (maya-chen) to a PTSD teaching case.
    // Case Engine supplies PTSD clinical_core; persona identity is randomized.
    default_persona_slug: null,
    randomization_level: "moderate",
    memory_mode: "case_isolated",
    grading_rubric: {
      pass_threshold: 70,
      outstanding_threshold: 90,
      critical_mistakes: ["forced trauma disclosure", "missed SI"],
    },
    report_template: {
      sections: ["risk", "safety_plan", "disposition"],
    },
    learning_objectives: [
      {
        category: "risk",
        statement: "Complete trauma-informed risk assessment",
      },
      {
        category: "skills",
        statement: "Titrate trauma content; avoid flooding",
      },
      {
        category: "documentation",
        statement: "Document disposition and safety plan",
      },
    ],
    clinical_competencies: [
      {
        competency_id: "safety",
        label: "Safety assessment",
        weight: 2,
        max_score: 5,
        critical: true,
        auto_deduction: 20,
      },
      {
        competency_id: "trauma_pacing",
        label: "Trauma pacing",
        weight: 1.5,
        max_score: 5,
      },
    ],
    enabled: true,
    version: 1,
  },
  {
    id: "e1000000-0000-4000-8000-000000000004",
    slug: "adult-bpd-crisis-en",
    name: "Adult BPD — Crisis Safety (English)",
    description:
      "DBT-informed crisis interview with affective instability and self-harm risk.",
    specialty: "emergency_psychiatry",
    target_learners: ["psychiatry_resident", "crisis_worker", "clinical_psychology"],
    estimated_duration_minutes: 30,
    difficulty: "advanced",
    language: "en-US",
    culture: "north_american_urban",
    therapy_modality: "dbt",
    primary_diagnosis_id: DISORDER_IDS.bpd,
    primary_diagnosis_slug: "bpd",
    allowed_comorbidity_slugs: ["mdd-recurrent-moderate", "ptsd"],
    excluded_diagnosis_slugs: ["delirium", "bipolar-mania"],
    severity: "moderate",
    risk_level: "high",
    assessment_type: "crisis_intervention",
    default_persona_slug: null,
    randomization_level: "moderate",
    memory_mode: "case_isolated",
    grading_rubric: {
      pass_threshold: 70,
      outstanding_threshold: 90,
      critical_mistakes: ["missed_self_harm", "invalidation_escalation"],
      automatic_deductions: { missed_self_harm: 20 },
    },
    report_template: { sections: ["risk", "alliance", "safety_plan"] },
    learning_objectives: [
      {
        category: "risk",
        statement: "Assess self-harm and SI without escalating affect",
      },
      {
        category: "therapeutic_alliance",
        statement: "Validate before change strategies",
      },
      {
        category: "differential_diagnosis",
        statement: "Differentiate BPD from CPTSD and bipolar mania",
      },
    ],
    clinical_competencies: [
      {
        competency_id: "safety",
        label: "Safety assessment",
        weight: 2,
        max_score: 5,
        critical: true,
      },
      {
        competency_id: "alliance",
        label: "Validation",
        weight: 1.5,
        max_score: 5,
      },
    ],
    enabled: true,
    version: 1,
  },
  {
    id: "e1000000-0000-4000-8000-000000000005",
    slug: "bipolar-mania-safety-en",
    name: "Bipolar Mania — Safety Assessment (English)",
    description:
      "Containment-focused assessment of manic episode with psychotic features.",
    specialty: "general_adult_psychiatry",
    target_learners: ["psychiatry_resident", "emergency_physician"],
    estimated_duration_minutes: 25,
    difficulty: "expert",
    language: "en-US",
    culture: "north_american_urban",
    therapy_modality: "crisis_intervention",
    primary_diagnosis_id: DISORDER_IDS.bipolarMania,
    primary_diagnosis_slug: "bipolar-mania",
    allowed_comorbidity_slugs: ["alcohol-use-disorder"],
    excluded_diagnosis_slugs: ["mdd-recurrent-moderate", "delirium"],
    severity: "severe",
    risk_level: "high",
    assessment_type: "risk_assessment",
    default_persona_slug: null,
    randomization_level: "low",
    memory_mode: "case_isolated",
    grading_rubric: {
      pass_threshold: 75,
      outstanding_threshold: 92,
      critical_mistakes: ["missing_sleep_inquiry", "antidepressant_only_plan"],
    },
    report_template: { sections: ["risk", "mse", "disposition"] },
    learning_objectives: [
      {
        category: "risk",
        statement: "Assess judgment, impulsivity, and harm risk in mania",
      },
      {
        category: "dsm_reasoning",
        statement: "Defend manic episode with psychotic features coding",
      },
      {
        category: "skills",
        statement: "Use brief containment questions without confrontation",
      },
    ],
    clinical_competencies: [
      {
        competency_id: "safety",
        label: "Safety",
        weight: 2,
        max_score: 5,
        critical: true,
      },
      {
        competency_id: "mse",
        label: "Mental status",
        weight: 1.5,
        max_score: 5,
      },
    ],
    enabled: true,
    version: 1,
  },
  {
    id: "e1000000-0000-4000-8000-000000000006",
    slug: "schizophrenia-initial-en",
    name: "Schizophrenia — Initial Assessment (English)",
    description:
      "Supportive psychosis assessment across positive, negative, and risk domains.",
    specialty: "general_adult_psychiatry",
    target_learners: ["psychiatry_resident", "clinical_psychology"],
    estimated_duration_minutes: 40,
    difficulty: "advanced",
    language: "en-US",
    culture: "north_american_urban",
    therapy_modality: "supportive",
    primary_diagnosis_id: DISORDER_IDS.schizophrenia,
    primary_diagnosis_slug: "schizophrenia",
    allowed_comorbidity_slugs: ["gad-with-panic"],
    excluded_diagnosis_slugs: ["delirium"],
    severity: "moderate",
    risk_level: "moderate",
    assessment_type: "initial_assessment",
    default_persona_slug: null,
    randomization_level: "moderate",
    memory_mode: "case_isolated",
    grading_rubric: {
      pass_threshold: 70,
      outstanding_threshold: 90,
      critical_mistakes: ["reality_confrontation", "missed_command_hallucinations"],
    },
    report_template: { sections: ["mse", "risk", "formulation"] },
    learning_objectives: [
      {
        category: "skills",
        statement: "Elicit psychotic symptoms without confrontation",
      },
      {
        category: "risk",
        statement: "Assess command hallucinations and harm risk",
      },
      {
        category: "differential_diagnosis",
        statement: "Differentiate schizophrenia from mood psychosis and delirium",
      },
    ],
    clinical_competencies: [
      {
        competency_id: "mse",
        label: "Psychosis MSE",
        weight: 1.5,
        max_score: 5,
        critical: true,
      },
      {
        competency_id: "safety",
        label: "Safety",
        weight: 1.5,
        max_score: 5,
      },
    ],
    enabled: true,
    version: 1,
  },
  {
    id: "e1000000-0000-4000-8000-000000000007",
    slug: "ocd-erp-assessment-en",
    name: "OCD — ERP-Informed Assessment (English)",
    description: "Map obsessions/compulsions and insight without reassurance loops.",
    specialty: "clinical_psychology",
    target_learners: ["clinical_psychology", "psychiatry_resident"],
    estimated_duration_minutes: 35,
    difficulty: "intermediate",
    language: "en-US",
    culture: "north_american_urban",
    therapy_modality: "exposure_therapy",
    primary_diagnosis_id: DISORDER_IDS.ocd,
    primary_diagnosis_slug: "ocd",
    allowed_comorbidity_slugs: ["gad-with-panic", "mdd-recurrent-moderate"],
    excluded_diagnosis_slugs: ["schizophrenia"],
    severity: "moderate",
    risk_level: "low",
    assessment_type: "initial_assessment",
    default_persona_slug: null,
    randomization_level: "moderate",
    memory_mode: "case_isolated",
    grading_rubric: {
      pass_threshold: 65,
      outstanding_threshold: 88,
      critical_mistakes: ["reassurance_loop", "forced_content"],
    },
    report_template: { sections: ["formulation", "erp_readiness"] },
    learning_objectives: [
      {
        category: "skills",
        statement: "Map obsession-compulsion cycle without reassurance",
      },
      {
        category: "dsm_reasoning",
        statement: "Defend OCD vs GAD/OCPD differential",
      },
      {
        category: "communication",
        statement: "Pace shameful content with empathic rapport",
      },
    ],
    clinical_competencies: [
      {
        competency_id: "formulation",
        label: "OCD formulation",
        weight: 1.5,
        max_score: 5,
        critical: true,
      },
      {
        competency_id: "alliance",
        label: "Alliance",
        weight: 1,
        max_score: 5,
      },
    ],
    enabled: true,
    version: 1,
  },
  {
    id: "e1000000-0000-4000-8000-000000000008",
    slug: "complex-ptsd-phase1-ar",
    name: "Complex PTSD — Phase-1 Safety (Arabic)",
    description:
      "Arabic Levantine phase-1 safety and affect regulation for ICD-11 CPTSD.",
    specialty: "general_adult_psychiatry",
    target_learners: ["psychiatry_resident", "counsellor", "clinical_psychology"],
    estimated_duration_minutes: 35,
    difficulty: "advanced",
    language: "ar-JO",
    culture: "levantine_arabic",
    therapy_modality: "supportive",
    primary_diagnosis_id: DISORDER_IDS.complexPtsd,
    primary_diagnosis_slug: "complex-ptsd",
    allowed_comorbidity_slugs: ["mdd-recurrent-moderate"],
    excluded_diagnosis_slugs: ["delirium"],
    severity: "severe",
    risk_level: "high",
    assessment_type: "risk_assessment",
    default_persona_slug: null,
    randomization_level: "low",
    memory_mode: "case_isolated",
    grading_rubric: {
      pass_threshold: 70,
      outstanding_threshold: 90,
      critical_mistakes: ["forced_trauma_disclosure", "dsm5_ptsd_only_coding"],
    },
    report_template: { sections: ["risk", "phase1", "icd11"] },
    learning_objectives: [
      {
        category: "risk",
        statement: "Complete phase-1 safety without flooding",
      },
      {
        category: "icd_reasoning",
        statement: "Map CPTSD to ICD-11 6B41 with DSO features",
      },
      {
        category: "communication",
        statement: "Conduct Arabic interview without locale leakage",
      },
    ],
    clinical_competencies: [
      {
        competency_id: "safety",
        label: "Safety",
        weight: 2,
        max_score: 5,
        critical: true,
      },
      {
        competency_id: "trauma_pacing",
        label: "Trauma pacing",
        weight: 1.5,
        max_score: 5,
      },
    ],
    enabled: true,
    version: 1,
  },
  {
    id: "e1000000-0000-4000-8000-000000000009",
    slug: "panic-osce-en",
    name: "Panic Disorder — OSCE (English)",
    description: "OSCE station for panic phenomenology and avoidance mapping.",
    specialty: "general_adult_psychiatry",
    target_learners: ["medical_student", "psychiatry_resident"],
    estimated_duration_minutes: 20,
    difficulty: "beginner",
    language: "en-US",
    culture: "north_american_urban",
    therapy_modality: "cbt",
    primary_diagnosis_id: DISORDER_IDS.panic,
    primary_diagnosis_slug: "panic-disorder",
    allowed_comorbidity_slugs: ["gad-with-panic", "mdd-recurrent-moderate"],
    excluded_diagnosis_slugs: ["schizophrenia"],
    severity: "moderate",
    risk_level: "low",
    assessment_type: "osce_examination",
    default_persona_slug: "jordan-hale",
    randomization_level: "low",
    memory_mode: "case_isolated",
    grading_rubric: {
      pass_threshold: 60,
      outstanding_threshold: 85,
      critical_mistakes: ["reassurance_loop", "missing_panic_phenomenology"],
    },
    report_template: { sections: ["osce_checklist", "communication"] },
    learning_objectives: [
      {
        category: "skills",
        statement: "Elicit unexpected panic attack criteria",
      },
      {
        category: "communication",
        statement: "Limit reassurance while remaining empathic",
      },
      {
        category: "differential_diagnosis",
        statement: "Screen medical mimics without over-reassurance",
      },
    ],
    clinical_competencies: [
      {
        competency_id: "anxiety_assessment",
        label: "Panic assessment",
        weight: 1.5,
        max_score: 5,
        critical: true,
      },
      {
        competency_id: "communication",
        label: "Communication",
        weight: 1.2,
        max_score: 5,
      },
    ],
    enabled: true,
    version: 1,
  },
  {
    id: "e1000000-0000-4000-8000-00000000000a",
    slug: "adult-mdd-followup-ar",
    name: "Adult MDD — Follow-up (Arabic)",
    description:
      "Arabic follow-up mood and risk review with bipolarity screen before AD discussion.",
    specialty: "general_adult_psychiatry",
    target_learners: ["psychiatry_resident", "gp", "counsellor"],
    estimated_duration_minutes: 30,
    difficulty: "intermediate",
    language: "ar-JO",
    culture: "levantine_arabic",
    therapy_modality: "cbt",
    primary_diagnosis_id: DISORDER_IDS.mdd,
    primary_diagnosis_slug: "mdd-recurrent-moderate",
    allowed_comorbidity_slugs: ["gad-with-panic"],
    excluded_diagnosis_slugs: ["bipolar-mania"],
    severity: "moderate",
    risk_level: "moderate",
    assessment_type: "follow_up",
    default_persona_slug: "maya-chen",
    randomization_level: "moderate",
    memory_mode: "case_isolated",
    grading_rubric: {
      pass_threshold: 65,
      outstanding_threshold: 88,
      critical_mistakes: ["ignoring_passive_si", "no_bipolar_screen"],
    },
    report_template: { sections: ["summary", "risk", "plan"] },
    learning_objectives: [
      {
        category: "risk",
        statement: "Reassess passive SI in Arabic without interrogation",
      },
      {
        category: "dsm_reasoning",
        statement: "Screen bipolarity before antidepressant discussion",
      },
      {
        category: "communication",
        statement: "Maintain Levantine register without English leakage",
      },
    ],
    clinical_competencies: [
      {
        competency_id: "safety",
        label: "Safety",
        weight: 1.5,
        max_score: 5,
        critical: true,
      },
      {
        competency_id: "communication",
        label: "Arabic communication",
        weight: 1.5,
        max_score: 5,
      },
    ],
    enabled: true,
    version: 1,
  },
];

export function findTemplateBySlug(
  slug: string,
): ClinicalScenarioTemplate | undefined {
  return BUILTIN_TEMPLATES.find((t) => t.slug === slug && t.enabled);
}

export function findTemplateById(
  id: string,
): ClinicalScenarioTemplate | undefined {
  return BUILTIN_TEMPLATES.find((t) => t.id === id && t.enabled);
}

export function listBuiltinTemplates(): ClinicalScenarioTemplate[] {
  return BUILTIN_TEMPLATES.filter((t) => t.enabled);
}
