-- Canonical migration recovered for Release Configuration Board reconciliation.
-- Source: production supabase_migrations.schema_migrations statements
-- (enriched only when production statements were empty/placeholder).

INSERT INTO public.cge_nodes (
  id, name, description, domain, difficulty, clinical_importance,
  learning_objectives, assessment_methods, mastery_threshold, mastery_min_samples,
  recommended_resources, estimated_training_hours, sort_order
) VALUES
('empathy', 'Empathy', 'Empathic communication', 'alliance', 'foundation', 8,
   '["Reflect affect","Validate"]'::jsonb,
   '["empathy_rubric"]'::jsonb, 70, 2,
   '["MI OARS"]'::jsonb, 1.5, 160),
('cbt_skills', 'CBT Skills', 'Cognitive behavioural interventions', 'therapy', 'intermediate', 8,
   '["Agenda","Thought records","Homework"]'::jsonb,
   '["cbt_session"]'::jsonb, 70, 3,
   '["Beck CT basics"]'::jsonb, 4, 170),
('dbt_skills', 'DBT Skills', 'Dialectical behaviour skills', 'therapy', 'advanced', 8,
   '["Validation","Skills coaching"]'::jsonb,
   '["dbt_session"]'::jsonb, 70, 3,
   '["DBT skills manual"]'::jsonb, 4, 180),
('act_skills', 'ACT Skills', 'Acceptance and commitment therapy', 'therapy', 'advanced', 7,
   '["Values","Defusion"]'::jsonb,
   '["act_session"]'::jsonb, 70, 3,
   '["ACT made simple"]'::jsonb, 3, 190),
('psychodynamic_interviewing', 'Psychodynamic Skills', 'Psychodynamic therapy skills', 'therapy', 'advanced', 7,
   '["Transference awareness","Interpretation timing"]'::jsonb,
   '["psychodynamic_session"]'::jsonb, 70, 3,
   '["Psychodynamic psychotherapy primer"]'::jsonb, 4, 200),
('supportive_therapy', 'Supportive Therapy', 'Supportive psychotherapy skills', 'therapy', 'intermediate', 7,
   '["Support ego function","Problem-solve"]'::jsonb,
   '["supportive_session"]'::jsonb, 70, 2,
   '["Supportive psychotherapy guide"]'::jsonb, 2, 210),
('motivational_interviewing', 'Motivational Interviewing', 'MI spirit and techniques', 'therapy', 'intermediate', 8,
   '["OARS","Rolling with resistance"]'::jsonb,
   '["mi_session"]'::jsonb, 70, 3,
   '["MI pocket guide"]'::jsonb, 3, 220),
('documentation', 'Clinical Documentation', 'Clinical documentation quality', 'professional', 'intermediate', 8,
   '["Accurate notes","Timely documentation"]'::jsonb,
   '["note_rubric"]'::jsonb, 70, 3,
   '["Documentation standards"]'::jsonb, 2, 230),
('case_summary', 'Case Summary', 'Concise case summary', 'professional', 'intermediate', 7,
   '["Synthesize key data"]'::jsonb,
   '["summary_rubric"]'::jsonb, 70, 2,
   '["Oral presentation guide"]'::jsonb, 1.5, 240),
('diagnostic_formulation', 'Diagnostic Formulation', 'Written diagnostic formulation', 'professional', 'advanced', 8,
   '["Write DSM/ICD formulation"]'::jsonb,
   '["formulation_rubric"]'::jsonb, 70, 3,
   '["Formulation templates"]'::jsonb, 2, 250),
('treatment_documentation', 'Treatment Documentation', 'Treatment plan documentation', 'professional', 'advanced', 7,
   '["Document plan and rationale"]'::jsonb,
   '["plan_doc_rubric"]'::jsonb, 70, 2,
   '["Treatment plan templates"]'::jsonb, 1.5, 260),
('psychoeducation', 'Psychoeducation', 'Patient education', 'treatment', 'intermediate', 7,
   '["Explain illness","Teach coping"]'::jsonb,
   '["edu_checklist"]'::jsonb, 70, 2,
   '["Psychoeducation scripts"]'::jsonb, 1.5, 270),
('professional_communication', 'Professional Communication', 'Clear professional communication', 'professional', 'foundation', 8,
   '["Handoffs","Collegial language"]'::jsonb,
   '["communication_rubric"]'::jsonb, 70, 2,
   '["SBAR"]'::jsonb, 1, 280),
('time_management', 'Time Management', 'Station / session time use', 'professional', 'foundation', 7,
   '["Prioritize","Close on time"]'::jsonb,
   '["timer_stations"]'::jsonb, 70, 2,
   '["OSCE time strategies"]'::jsonb, 1, 290),
('ethical_decision_making', 'Ethical Decision Making', 'Ethics and professionalism', 'professional', 'intermediate', 9,
   '["Consent","Confidentiality limits"]'::jsonb,
   '["ethics_cases"]'::jsonb, 75, 2,
   '["APA ethics code"]'::jsonb, 2, 300),
('cultural_competence', 'Cultural Competence', 'Culturally responsive care', 'professional', 'intermediate', 8,
   '["Elicit explanatory model","Adapt care"]'::jsonb,
   '["culture_cases"]'::jsonb, 70, 2,
   '["Cultural formulation interview"]'::jsonb, 2, 310),
('family_interviewing', 'Family Interviewing', 'Family / systems assessment', 'assessment', 'advanced', 7,
   '["Engage family","Map systems"]'::jsonb,
   '["family_session"]'::jsonb, 70, 2,
   '["Family assessment primer"]'::jsonb, 2, 320)
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  domain = EXCLUDED.domain,
  difficulty = EXCLUDED.difficulty,
  clinical_importance = EXCLUDED.clinical_importance,
  mastery_threshold = EXCLUDED.mastery_threshold,
  updated_at = now();
