-- Canonical migration recovered for Release Configuration Board reconciliation.
-- Source: production supabase_migrations.schema_migrations statements
-- (enriched only when production statements were empty/placeholder).

INSERT INTO public.cge_nodes (
  id, name, description, domain, difficulty, clinical_importance,
  learning_objectives, assessment_methods, mastery_threshold, mastery_min_samples,
  recommended_resources, estimated_training_hours, sort_order
) VALUES
('clinical_communication', 'Clinical Communication', 'Foundational clinical communication', 'alliance', 'foundation', 9,
   '["Establish rapport","Use clear language","Manage silence"]'::jsonb,
   '["observed_interview","osce"]'::jsonb, 70, 3,
   '["Clinical interviewing basics"]'::jsonb, 2, 5),
('diagnostic_interview', 'Diagnostic Interview', 'Structured psychiatric interview', 'assessment', 'foundation', 10,
   '["Structure interview","Elicit HPI","Cover psychiatric ROS"]'::jsonb,
   '["simulated_patient","checklist"]'::jsonb, 70, 3,
   '["Shea psychiatric interview"]'::jsonb, 3, 10),
('mental_status_examination', 'Mental Status Examination', 'MSE completeness and accuracy', 'assessment', 'foundation', 10,
   '["Cover MSE domains","Document accurately"]'::jsonb,
   '["mse_checklist"]'::jsonb, 70, 3,
   '["MSE pocket card"]'::jsonb, 2, 20),
('dsm5_reasoning', 'DSM-5 Diagnostic Reasoning', 'Apply DSM-5 criteria', 'diagnosis', 'intermediate', 9,
   '["Map symptoms to criteria","Identify specifiers"]'::jsonb,
   '["case_formulation"]'::jsonb, 70, 3,
   '["DSM-5-TR"]'::jsonb, 4, 30),
('icd11_reasoning', 'ICD-11 Diagnostic Reasoning', 'Apply ICD-11 criteria', 'diagnosis', 'intermediate', 8,
   '["Map to ICD-11","Crosswalk DSM"]'::jsonb,
   '["case_formulation"]'::jsonb, 70, 3,
   '["ICD-11 CDDR"]'::jsonb, 3, 40),
('differential_diagnosis', 'Differential Diagnosis', 'Generate and rule out differentials', 'diagnosis', 'advanced', 10,
   '["Generate differentials","Rule-out systematically"]'::jsonb,
   '["ambiguity_cases"]'::jsonb, 70, 4,
   '["DSM differential trees"]'::jsonb, 4, 50),
('case_formulation', 'Case Formulation', 'Integrative case formulation', 'diagnosis', 'advanced', 9,
   '["Integrate biopsychosocial factors"]'::jsonb,
   '["written_formulation"]'::jsonb, 70, 3,
   '["Formulation worksheets"]'::jsonb, 3, 55),
('treatment_planning', 'Treatment Planning', 'Collaborative treatment plans', 'treatment', 'advanced', 10,
   '["Prioritize problems","Match interventions"]'::jsonb,
   '["plan_rubric"]'::jsonb, 70, 3,
   '["APA treatment guidelines"]'::jsonb, 3, 60),
('medication_management', 'Medication Management', 'Psychopharmacology decisions', 'treatment', 'advanced', 9,
   '["Choose agents","Counsel side effects"]'::jsonb,
   '["med_cases"]'::jsonb, 75, 4,
   '["Stahl essential psychopharmacology"]'::jsonb, 5, 70),
('follow_up_planning', 'Follow-up Planning', 'Disposition and follow-up', 'treatment', 'intermediate', 7,
   '["Set follow-up","Safety net"]'::jsonb,
   '["disposition_checklist"]'::jsonb, 70, 2,
   '["Care coordination primer"]'::jsonb, 1.5, 80),
('risk_screening', 'Risk Screening', 'Initial risk screening', 'safety', 'foundation', 10,
   '["Screen SI/HI","Screen substances"]'::jsonb,
   '["screening_checklist"]'::jsonb, 70, 3,
   '["SAFE-T"]'::jsonb, 2, 90),
('risk_assessment', 'Risk Assessment', 'General risk formulation', 'safety', 'intermediate', 10,
   '["Formulate risk","Protective factors"]'::jsonb,
   '["risk_cases"]'::jsonb, 70, 3,
   '["Structured risk formulation"]'::jsonb, 3, 100),
('suicide_assessment', 'Suicide Assessment', 'SI inquiry and safety planning', 'safety', 'advanced', 10,
   '["Ask about SI specifically","Assess plan/means/intent"]'::jsonb,
   '["si_stations"]'::jsonb, 75, 4,
   '["C-SSRS","SAFE-T"]'::jsonb, 4, 110),
('violence_assessment', 'Violence Assessment', 'Violence / harm-to-others', 'safety', 'advanced', 9,
   '["Assess HI","Identify targets"]'::jsonb,
   '["violence_stations"]'::jsonb, 75, 3,
   '["HCR-20 overview"]'::jsonb, 3, 120),
('safety_planning', 'Safety Planning', 'Collaborative safety planning', 'safety', 'advanced', 10,
   '["Build safety plan","Means restriction"]'::jsonb,
   '["safety_plan_rubric"]'::jsonb, 75, 3,
   '["Stanley-Brown safety plan"]'::jsonb, 2, 130),
('emergency_psychiatry', 'Emergency Psychiatry', 'Acute / emergency psychiatry', 'safety', 'expert', 10,
   '["Stabilize","Disposition"]'::jsonb,
   '["crisis_cases"]'::jsonb, 80, 4,
   '["Emergency psychiatry handbook"]'::jsonb, 5, 140),
('therapeutic_alliance', 'Therapeutic Alliance', 'Collaborative working alliance', 'alliance', 'foundation', 9,
   '["Build collaboration","Repair ruptures"]'::jsonb,
   '["alliance_markers"]'::jsonb, 70, 3,
   '["Alliance literature summary"]'::jsonb, 2, 150)
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  domain = EXCLUDED.domain,
  difficulty = EXCLUDED.difficulty,
  clinical_importance = EXCLUDED.clinical_importance,
  mastery_threshold = EXCLUDED.mastery_threshold,
  updated_at = now();
